import type { Metadata } from "next";
import monumentExtended from 'next/font/local';
import satoshiBold from 'next/font/local';
import satoshiRegular from 'next/font/local';
import satoshiMedium from 'next/font/local';
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"],
  weight: ['400']
 });

 // Font files located inside of `public`
const monument = monumentExtended({
  src: '../public/fonts/MonumentExtended-Regular.woff2',
  display: 'swap',
  variable: '--font-monument',
});
const satoshibold = satoshiBold({
  src: '../public/fonts/Satoshi-Bold.woff2',
  display: 'swap',
  variable: '--font-satoshibold',
});
const satoshimedium = satoshiMedium({
  src: '../public/fonts/Satoshi-Bold.woff2',
  display: 'swap',
  variable: '--font-satoshimedium',
});
const satoshiregular = satoshiRegular({
  src: '../public/fonts/Satoshi-Regular.woff2',
  display: 'swap',
  variable: '--font-satoshiregular',
});

export const metadata: Metadata = {
  title: "front-end-assignment-figma",
  description: "Generated by front-end-assignment-figma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${monument.variable} ${satoshibold.variable} ${satoshimedium.variable} 
      ${satoshiregular.variable}`}>
        {children}
      </body>
    </html>
  );
}
